load:
  task: ./configs/task_allocation_sample/task.yaml
  task_dependency: ./configs/task_allocation_sample/task_dependency.yaml
  module_type: ./configs/task_allocation_sample/module_type.yaml
  module: ./configs/task_allocation_sample/module.yaml
  robot_type: ./configs/task_allocation_sample/robot_type.yaml
  robot: ./configs/task_allocation_sample/robot.yaml
  map: ./configs/task_allocation_sample/map.yaml
  risk_scenario: ./configs/task_allocation_sample/risk_scenario.yaml
  task_priority: ./configs/task_allocation_sample/task_priority.yaml

simulation:
  max_step: 50
  training_scenarios: [[s_000], [s_001], [s_002], [s_003]]
  varidate_scenarios: [s_004]

task_allocation:
  population_size: 10
  generations: 200
  seed: 1234
