body_00:  # モジュール名（任意）
  module_type: Body  # モジュール型名 Module_type.yamlに記載されているもののみ
  coordinate: [0.0, 0.0]  # モジュールの座標
  battery: 1  # モジュールのバッテリー残量
  state: 0  # モジュールの状態 0: 正常 1: 異常
body_01:
  module_type: Body
  coordinate: [0.0, 0.0]
  battery: 1
  state: 0
body_02:
  module_type: Body
  coordinate: [0.0, 0.0]
  battery: 1
  state: 0
body_03:
  module_type: Body
  coordinate: [0.0, 0.0]
  battery: 1
  state: 0
body_04:
  module_type: Body
  coordinate: [0.0, 0.0]
  battery: 1
  state: 0
body_05:
  module_type: Body
  coordinate: [0.0, 0.0]
  battery: 1
  state: 0
body_06:
  module_type: Body
  coordinate: [0.0, 0.0]
  battery: 1
  state: 0
body_07:
  module_type: Body
  coordinate: [0.0, 0.0]
  battery: 1
  state: 0
body_08:
  module_type: Body
  coordinate: [0.0, 0.0]
  battery: 1
  state: 0
body_09:
  module_type: Body
  coordinate: [0.0, 0.0]
  battery: 1
  state: 0

limb_00:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
  state: 0
limb_01:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
  state: 0
limb_02:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
  state: 0
limb_03:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
  state: 0
limb_04:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
  state: 0
limb_05:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
  state: 0
limb_06:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
  state: 0
limb_07:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
  state: 0
limb_08:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
  state: 0
limb_09:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
  state: 0
limb_10:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
  state: 0
limb_11:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
  state: 0
limb_12:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
  state: 0
limb_13:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
  state: 0
limb_14:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
  state: 0
limb_15:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
  state: 0
limb_16:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
  state: 0
limb_17:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
  state: 0
limb_18:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
  state: 0
limb_19:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
  state: 0
limb_20:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
  state: 0
limb_21:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
  state: 0
limb_22:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
  state: 0
limb_23:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
  state: 0
limb_24:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
  state: 0
limb_25:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
  state: 0
limb_26:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
  state: 0
limb_27:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
  state: 0
limb_28:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
  state: 0
limb_29:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
  state: 0
limb_30:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
  state: 0
limb_31:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
  state: 0
limb_32:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
  state: 0
limb_33:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
  state: 0
limb_34:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
  state: 0
limb_35:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
  state: 0
limb_36:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
  state: 0
limb_37:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
  state: 0
limb_38:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
  state: 0
limb_39:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
  state: 0
limb_40:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
  state: 0
limb_41:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
  state: 0
limb_42:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
  state: 0
limb_43:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
  state: 0
limb_44:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
  state: 0
limb_45:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
  state: 0
limb_46:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
  state: 0
limb_47:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
  state: 0
limb_48:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
  state: 0
limb_49:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
  state: 0

ende_00:
  module_type: EndE
  coordinate: [0.0, 0.0]
  battery: 1
  state: 0
ende_01:
  module_type: EndE
  coordinate: [0.0, 0.0]
  battery: 1
  state: 0
ende_02:
  module_type: EndE
  coordinate: [0.0, 0.0]
  battery: 1
  state: 0
ende_03:
  module_type: EndE
  coordinate: [0.0, 0.0]
  battery: 1
  state: 0
ende_04:
  module_type: EndE
  coordinate: [0.0, 0.0]
  battery: 1
  state: 0
ende_05:
  module_type: EndE
  coordinate: [0.0, 0.0]
  battery: 1
  state: 0
ende_06:
  module_type: EndE
  coordinate: [0.0, 0.0]
  battery: 1
  state: 0
ende_07:
  module_type: EndE
  coordinate: [0.0, 0.0]
  battery: 1
  state: 0
ende_08:
  module_type: EndE
  coordinate: [0.0, 0.0]
  battery: 1
  state: 0
ende_09:
  module_type: EndE
  coordinate: [0.0, 0.0]
  battery: 1
  state: 0
ende_10:
  module_type: EndE
  coordinate: [0.0, 0.0]
  battery: 1
  state: 0
ende_11:
  module_type: EndE
  coordinate: [0.0, 0.0]
  battery: 1
  state: 0
ende_12:
  module_type: EndE
  coordinate: [0.0, 0.0]
  battery: 1
  state: 0
ende_13:
  module_type: EndE
  coordinate: [0.0, 0.0]
  battery: 1
  state: 0
ende_14:
  module_type: EndE
  coordinate: [0.0, 0.0]
  battery: 1
  state: 0
ende_15:
  module_type: EndE
  coordinate: [0.0, 0.0]
  battery: 1
  state: 0
ende_16:
  module_type: EndE
  coordinate: [0.0, 0.0]
  battery: 1
  state: 0
ende_17:
  module_type: EndE
  coordinate: [0.0, 0.0]
  battery: 1
  state: 0
ende_18:
  module_type: EndE
  coordinate: [0.0, 0.0]
  battery: 1
  state: 0
ende_19:
  module_type: EndE
  coordinate: [0.0, 0.0]
  battery: 1
  state: 0

wheel_00:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
  state: 0
wheel_01:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
  state: 0
wheel_02:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
  state: 0
wheel_03:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
  state: 0
wheel_04:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
  state: 0
wheel_05:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
  state: 0
wheel_06:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
  state: 0
wheel_07:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
  state: 0
wheel_08:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
  state: 0
wheel_09:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
  state: 0
wheel_10:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
  state: 0
wheel_11:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
  state: 0
wheel_12:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
  state: 0
wheel_13:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
  state: 0
wheel_14:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
  state: 0
wheel_15:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
  state: 0
wheel_16:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
  state: 0
wheel_17:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
  state: 0
wheel_18:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
  state: 0
wheel_19:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
  state: 0
wheel_20:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
  state: 0
wheel_21:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
  state: 0
wheel_22:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
  state: 0
wheel_23:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
  state: 0
wheel_24:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
  state: 0
wheel_25:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
  state: 0
wheel_26:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
  state: 0
wheel_27:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
  state: 0
wheel_28:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
  state: 0
wheel_29:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
  state: 0
wheel_30:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
  state: 0
wheel_31:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
  state: 0
wheel_32:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
  state: 0
wheel_33:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
  state: 0
wheel_34:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
  state: 0
