m_000:
  name: m_000
  module_type: Body
  coordinate:
  - 0.0
  - 0.0
  battery: 1
  operating_time: 0.0
  state: ACTIVE
m_001:
  name: m_001
  module_type: Body
  coordinate:
  - 0.0
  - 0.0
  battery: 1
  operating_time: 0.0
  state: ACTIVE
m_002:
  name: m_002
  module_type: Body
  coordinate:
  - 0.0
  - 0.0
  battery: 1
  operating_time: 0.0
  state: ACTIVE
m_003:
  name: m_003
  module_type: Body
  coordinate:
  - 0.0
  - 0.0
  battery: 1
  operating_time: 0.0
  state: ACTIVE
m_004:
  name: m_004
  module_type: Body
  coordinate:
  - 0.0
  - 0.0
  battery: 1
  operating_time: 0.0
  state: ACTIVE
m_005:
  name: m_005
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: ACTIVE
m_006:
  name: m_006
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: ACTIVE
m_007:
  name: m_007
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: ACTIVE
m_008:
  name: m_008
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: ACTIVE
m_009:
  name: m_009
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: ACTIVE
m_010:
  name: m_010
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: ACTIVE
m_011:
  name: m_011
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: ACTIVE
m_012:
  name: m_012
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: ACTIVE
m_013:
  name: m_013
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: ACTIVE
m_014:
  name: m_014
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: ACTIVE
m_015:
  name: m_015
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: ACTIVE
m_016:
  name: m_016
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: ACTIVE
m_017:
  name: m_017
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: ACTIVE
m_018:
  name: m_018
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: ACTIVE
m_019:
  name: m_019
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: ACTIVE
m_020:
  name: m_020
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: ACTIVE
m_021:
  name: m_021
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: ACTIVE
m_022:
  name: m_022
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: ACTIVE
m_023:
  name: m_023
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: ACTIVE
m_024:
  name: m_024
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: ACTIVE
m_025:
  name: m_025
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: ACTIVE
m_026:
  name: m_026
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: ACTIVE
m_027:
  name: m_027
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: ACTIVE
m_028:
  name: m_028
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: ACTIVE
m_029:
  name: m_029
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: ACTIVE
m_030:
  name: m_030
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: ACTIVE
m_031:
  name: m_031
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: ACTIVE
m_032:
  name: m_032
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: ACTIVE
m_033:
  name: m_033
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: ACTIVE
m_034:
  name: m_034
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: ACTIVE
m_035:
  name: m_035
  module_type: EndE
  coordinate:
  - 0.0
  - 0.0
  battery: 1
  operating_time: 0.0
  state: ACTIVE
m_036:
  name: m_036
  module_type: EndE
  coordinate:
  - 0.0
  - 0.0
  battery: 1
  operating_time: 0.0
  state: ACTIVE
m_037:
  name: m_037
  module_type: EndE
  coordinate:
  - 0.0
  - 0.0
  battery: 1
  operating_time: 0.0
  state: ACTIVE
m_038:
  name: m_038
  module_type: EndE
  coordinate:
  - 0.0
  - 0.0
  battery: 1
  operating_time: 0.0
  state: ACTIVE
m_039:
  name: m_039
  module_type: EndE
  coordinate:
  - 0.0
  - 0.0
  battery: 1
  operating_time: 0.0
  state: ACTIVE
m_040:
  name: m_040
  module_type: EndE
  coordinate:
  - 0.0
  - 0.0
  battery: 1
  operating_time: 0.0
  state: ACTIVE
m_041:
  name: m_041
  module_type: EndE
  coordinate:
  - 0.0
  - 0.0
  battery: 1
  operating_time: 0.0
  state: ACTIVE
m_042:
  name: m_042
  module_type: EndE
  coordinate:
  - 0.0
  - 0.0
  battery: 1
  operating_time: 0.0
  state: ACTIVE
m_043:
  name: m_043
  module_type: EndE
  coordinate:
  - 0.0
  - 0.0
  battery: 1
  operating_time: 0.0
  state: ACTIVE
m_044:
  name: m_044
  module_type: EndE
  coordinate:
  - 0.0
  - 0.0
  battery: 1
  operating_time: 0.0
  state: ACTIVE
m_045:
  name: m_045
  module_type: Wheel
  coordinate:
  - 0.0
  - 0.0
  battery: 15
  operating_time: 0.0
  state: ACTIVE
m_046:
  name: m_046
  module_type: Wheel
  coordinate:
  - 0.0
  - 0.0
  battery: 15
  operating_time: 0.0
  state: ACTIVE
m_047:
  name: m_047
  module_type: Wheel
  coordinate:
  - 0.0
  - 0.0
  battery: 15
  operating_time: 0.0
  state: ACTIVE
m_048:
  name: m_048
  module_type: Wheel
  coordinate:
  - 0.0
  - 0.0
  battery: 15
  operating_time: 0.0
  state: ACTIVE
m_049:
  name: m_049
  module_type: Wheel
  coordinate:
  - 0.0
  - 0.0
  battery: 15
  operating_time: 0.0
  state: ACTIVE
m_050:
  name: m_050
  module_type: Wheel
  coordinate:
  - 0.0
  - 0.0
  battery: 15
  operating_time: 0.0
  state: ACTIVE
m_051:
  name: m_051
  module_type: Wheel
  coordinate:
  - 0.0
  - 0.0
  battery: 15
  operating_time: 0.0
  state: ACTIVE
m_052:
  name: m_052
  module_type: Wheel
  coordinate:
  - 0.0
  - 0.0
  battery: 15
  operating_time: 0.0
  state: ACTIVE
m_053:
  name: m_053
  module_type: Wheel
  coordinate:
  - 0.0
  - 0.0
  battery: 15
  operating_time: 0.0
  state: ACTIVE
m_054:
  name: m_054
  module_type: Wheel
  coordinate:
  - 0.0
  - 0.0
  battery: 15
  operating_time: 0.0
  state: ACTIVE
m_055:
  name: m_055
  module_type: Wheel
  coordinate:
  - 0.0
  - 0.0
  battery: 15
  operating_time: 0.0
  state: ACTIVE
m_056:
  name: m_056
  module_type: Wheel
  coordinate:
  - 0.0
  - 0.0
  battery: 15
  operating_time: 0.0
  state: ACTIVE
m_057:
  name: m_057
  module_type: Wheel
  coordinate:
  - 0.0
  - 0.0
  battery: 15
  operating_time: 0.0
  state: ACTIVE
m_058:
  name: m_058
  module_type: Wheel
  coordinate:
  - 0.0
  - 0.0
  battery: 15
  operating_time: 0.0
  state: ACTIVE
m_059:
  name: m_059
  module_type: Wheel
  coordinate:
  - 0.0
  - 0.0
  battery: 15
  operating_time: 0.0
  state: ACTIVE
m_060:
  name: m_060
  module_type: Wheel
  coordinate:
  - 0.0
  - 0.0
  battery: 15
  operating_time: 0.0
  state: ACTIVE
m_061:
  name: m_061
  module_type: Wheel
  coordinate:
  - 0.0
  - 0.0
  battery: 15
  operating_time: 0.0
  state: ACTIVE
m_062:
  name: m_062
  module_type: Wheel
  coordinate:
  - 0.0
  - 0.0
  battery: 15
  operating_time: 0.0
  state: ACTIVE
m_063:
  name: m_063
  module_type: Wheel
  coordinate:
  - 0.0
  - 0.0
  battery: 15
  operating_time: 0.0
  state: ACTIVE
m_064:
  name: m_064
  module_type: Wheel
  coordinate:
  - 0.0
  - 0.0
  battery: 15
  operating_time: 0.0
  state: ACTIVE
