body_00:  # モジュール名（任意）
  module_type: Body  # モジュール型名 Module_type.yamlに記載されているもののみ
  coordinate: [0.0, 0.0]  # モジュールの座標
  battery: 3  # モジュールのバッテリー残量
  state: 0  # モジュールの状態 0: 正常 1: 異常
body_01:
  module_type: Body
  coordinate: [0.0, 0.0]
  battery: 3
body_02:
  module_type: Body
  coordinate: [0.0, 0.0]
  battery: 3
body_03:
  module_type: Body
  coordinate: [0.0, 0.0]
  battery: 3
body_04:
  module_type: Body
  coordinate: [0.0, 0.0]
  battery: 3
body_05:
  module_type: Body
  coordinate: [0.0, 0.0]
  battery: 3
body_06:
  module_type: Body
  coordinate: [0.0, 0.0]
  battery: 3
body_07:
  module_type: Body
  coordinate: [0.0, 0.0]
  battery: 3
body_08:
  module_type: Body
  coordinate: [0.0, 0.0]
  battery: 3
body_09:
  module_type: Body
  coordinate: [0.0, 0.0]
  battery: 3

limb_00:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
limb_01:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
limb_02:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
limb_03:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
limb_04:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
limb_05:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
limb_06:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
limb_07:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
limb_08:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
limb_09:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
limb_10:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
limb_11:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
limb_12:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
limb_13:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
limb_14:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
limb_15:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
limb_16:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
limb_17:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
limb_18:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
limb_19:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
limb_20:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
limb_21:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
limb_22:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
limb_23:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
limb_24:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
limb_25:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
limb_26:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
limb_27:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
limb_28:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
limb_29:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
limb_30:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
limb_31:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
limb_32:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
limb_33:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
limb_34:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
limb_35:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
limb_36:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
limb_37:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
limb_38:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
limb_39:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
limb_40:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
limb_41:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
limb_42:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
limb_43:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
limb_44:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
limb_45:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
limb_46:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
limb_47:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
limb_48:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5
limb_49:
  module_type: Limb
  coordinate: [0.0, 0.0]
  battery: 5

ende_00:
  module_type: EndE
  coordinate: [0.0, 0.0]
  battery: 1
ende_01:
  module_type: EndE
  coordinate: [0.0, 0.0]
  battery: 1
ende_02:
  module_type: EndE
  coordinate: [0.0, 0.0]
  battery: 1
ende_03:
  module_type: EndE
  coordinate: [0.0, 0.0]
  battery: 1
ende_04:
  module_type: EndE
  coordinate: [0.0, 0.0]
  battery: 1
ende_05:
  module_type: EndE
  coordinate: [0.0, 0.0]
  battery: 1
ende_06:
  module_type: EndE
  coordinate: [0.0, 0.0]
  battery: 1
ende_07:
  module_type: EndE
  coordinate: [0.0, 0.0]
  battery: 1
ende_08:
  module_type: EndE
  coordinate: [0.0, 0.0]
  battery: 1
ende_09:
  module_type: EndE
  coordinate: [0.0, 0.0]
  battery: 1
ende_10:
  module_type: EndE
  coordinate: [0.0, 0.0]
  battery: 1
ende_11:
  module_type: EndE
  coordinate: [0.0, 0.0]
  battery: 1
ende_12:
  module_type: EndE
  coordinate: [0.0, 0.0]
  battery: 1
ende_13:
  module_type: EndE
  coordinate: [0.0, 0.0]
  battery: 1
ende_14:
  module_type: EndE
  coordinate: [0.0, 0.0]
  battery: 1
ende_15:
  module_type: EndE
  coordinate: [0.0, 0.0]
  battery: 1
ende_16:
  module_type: EndE
  coordinate: [0.0, 0.0]
  battery: 1
ende_17:
  module_type: EndE
  coordinate: [0.0, 0.0]
  battery: 1
ende_18:
  module_type: EndE
  coordinate: [0.0, 0.0]
  battery: 1
ende_19:
  module_type: EndE
  coordinate: [0.0, 0.0]
  battery: 1

wheel_00:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
wheel_01:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
wheel_02:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
wheel_03:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
wheel_04:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
wheel_05:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
wheel_06:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
wheel_07:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
wheel_08:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
wheel_09:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
wheel_10:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
wheel_11:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
wheel_12:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
wheel_13:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
wheel_14:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
wheel_15:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
wheel_16:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
wheel_17:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
wheel_18:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
wheel_19:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
wheel_20:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
wheel_21:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
wheel_22:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
wheel_23:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
wheel_24:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
wheel_25:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
wheel_26:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
wheel_27:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
wheel_28:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
wheel_29:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
wheel_30:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
wheel_31:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
wheel_32:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
wheel_33:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
wheel_34:
  module_type: Wheel
  coordinate: [0.0, 0.0]
  battery: 15
