t_000:
  name: t_000
  class: Transport
  coordinate:
  - 0.0
  - 0.0
  required_performance:
    TRANSPORT: 12.0
    MANUFACTURE: 5.0
    MOBILITY: 11.0
  origin_coordinate:
  - 0.0
  - 0.0
  destination_coordinate:
  - 6.0
  - 8.0
  transportability: 1.0
  total_workload: 10.0
  completed_workload: 0.0
t_001:
  name: t_001
  class: Transport
  coordinate:
  - 0.0
  - 0.0
  required_performance:
    TRANSPORT: 12.0
    MANUFACTURE: 5.0
    MOBILITY: 11.0
  origin_coordinate:
  - 0.0
  - 0.0
  destination_coordinate:
  - 6.0
  - 8.0
  transportability: 1.0
  total_workload: 10.0
  completed_workload: 0.0
t_002:
  name: t_002
  class: Transport
  coordinate:
  - 0.0
  - 0.0
  required_performance:
    TRANSPORT: 12.0
    MANUFACTURE: 5.0
    MOBILITY: 11.0
  origin_coordinate:
  - 0.0
  - 0.0
  destination_coordinate:
  - 0.0
  - 5.0
  transportability: 2.0
  total_workload: 10.0
  completed_workload: 0.0
t_003:
  name: t_003
  class: Transport
  coordinate:
  - 0.0
  - 0.0
  required_performance:
    TRANSPORT: 12.0
    MANUFACTURE: 5.0
    MOBILITY: 11.0
  origin_coordinate:
  - 0.0
  - 0.0
  destination_coordinate:
  - 6.0
  - 8.0
  transportability: 1.0
  total_workload: 10.0
  completed_workload: 0.0
t_004:
  name: t_004
  class: Transport
  coordinate:
  - 0.0
  - 0.0
  required_performance:
    TRANSPORT: 12.0
    MANUFACTURE: 5.0
    MOBILITY: 11.0
  origin_coordinate:
  - 0.0
  - 0.0
  destination_coordinate:
  - 6.0
  - 8.0
  transportability: 1.0
  total_workload: 10.0
  completed_workload: 0.0
t_005:
  name: t_005
  class: Manufacture
  coordinate:
  - 6.0
  - 8.0
  required_performance:
    TRANSPORT: 9.0
    MANUFACTURE: 15.0
    MOBILITY: 5.0
  total_workload: 10.0
  completed_workload: 0.0
t_006:
  name: t_006
  class: Manufacture
  coordinate:
  - 0.0
  - 5.0
  required_performance:
    TRANSPORT: 9.0
    MANUFACTURE: 15.0
    MOBILITY: 5.0
  total_workload: 10.0
  completed_workload: 0.0
t_007:
  name: t_007
  class: Manufacture
  coordinate:
  - 6.0
  - 8.0
  required_performance:
    TRANSPORT: 9.0
    MANUFACTURE: 15.0
    MOBILITY: 5.0
  total_workload: 10.0
  completed_workload: 0.0
t_008:
  name: t_008
  class: Manufacture
  coordinate:
  - 0.0
  - 5.0
  required_performance:
    TRANSPORT: 9.0
    MANUFACTURE: 15.0
    MOBILITY: 5.0
  total_workload: 10.0
  completed_workload: 0.0
t_009:
  name: t_009
  class: Manufacture
  coordinate:
  - -5.0
  - 0.0
  required_performance:
    TRANSPORT: 9.0
    MANUFACTURE: 15.0
    MOBILITY: 5.0
  total_workload: 10.0
  completed_workload: 0.0
