i_t_000:  # タスクの名前（任意）
  # インフレータブル構造物の運搬
  class: Transport  # タスクのクラス (Transport, Manufacture, or Assemble)
  coordinate: [0.0, 0.0]  # タスクの座標
  total_workload: 10  # タスクの総作業量
  completed_workload: 0  # タスクの完了作業量
  task_dependency: []  # タスクの依存関係 (このファイル内でこのタスクより前に書いてあること)
  required_performance:  # タスクの必要能力(RobotPerformanceAttributesの属性名のみ)
    TRANSPORT: 12 # transport
    MANUFACTURE: 0 # manufacture
  other_attrs:
    category: Inflatable
  origin_coordinate: [0.0, 0.0]  # タスクの始点座標
  destination_coordinate: [5.0, 5.0]  # タスクの終点座標
  transportability: 0.5  # タスクの運搬難度（0.0~1.0）
i_m_000: # インフレータブル構造物の展開準備
  class: Manufacture
  coordinate: [5.0, 5.0]
  total_workload: 5
  completed_workload: 0
  task_dependency: [i_t_000]
  required_performance: 
    TRANSPORT: 0 # transport
    MANUFACTURE: 6 # manufacture
  other_attrs:
    category: Inflatable
i_m_001: # インフレータブル構造物の展開補助
  class: Manufacture
  coordinate: [5.0, 5.0]
  total_workload: 8
  completed_workload: 0
  task_dependency: [i_t_000, i_m_000]
  required_performance: 
    TRANSPORT: 0 # transport
    MANUFACTURE: 10 # manufacture
  other_attrs:
    category: Inflatable
s_t_000: # 太陽光発電パネルの運搬
  class: Transport
  coordinate: [0.0, 0.0]
  total_workload: 2.5
  completed_workload: 0
  task_dependency: []
  required_performance: 
    TRANSPORT: 3 # transport
    MANUFACTURE: 0 # manufacture
  other_attrs:
    category: Solar
  origin_coordinate: [0.0, 0.0]  # タスクの始点座標
  destination_coordinate: [0.0, 5.0]  # タスクの終点座標
  transportability: 1.0  # タスクの運搬難度（0.0~1.0）
s_t_001: # 太陽光発電パネルの運搬
  class: Transport
  coordinate: [0.0, 0.0]
  total_workload: 2.5
  completed_workload: 0
  task_dependency: []
  required_performance: 
    TRANSPORT: 3 # transport
    MANUFACTURE: 0 # manufacture
  other_attrs:
    category: Solar
  origin_coordinate: [0.0, 0.0]  # タスクの始点座標
  destination_coordinate: [0.0, 5.0]  # タスクの終点座標
  transportability: 1.0  # タスクの運搬難度（0.0~1.0）
s_t_002: # 太陽光発電パネルの運搬
  class: Transport
  coordinate: [0.0, 0.0]
  total_workload: 2.5
  completed_workload: 0
  task_dependency: []
  required_performance: 
    TRANSPORT: 3 # transport
    MANUFACTURE: 0 # manufacture
  other_attrs:
    category: Solar
  origin_coordinate: [0.0, 0.0]  # タスクの始点座標
  destination_coordinate: [0.0, 5.0]  # タスクの終点座標
  transportability: 1.0  # タスクの運搬難度（0.0~1.0）
s_t_003: # 太陽光発電パネルの運搬
  class: Transport
  coordinate: [0.0, 0.0]
  total_workload: 2.5
  completed_workload: 0
  task_dependency: []
  required_performance: 
    TRANSPORT: 3 # transport
    MANUFACTURE: 0 # manufacture
  other_attrs:
    category: Solar
  origin_coordinate: [0.0, 0.0]  # タスクの始点座標
  destination_coordinate: [0.0, 5.0]  # タスクの終点座標
  transportability: 1.0  # タスクの運搬難度（0.0~1.0）
s_m_000: # 太陽光発電パネルの展開
  class: Manufacture
  coordinate: [0.0, 5.0]
  total_workload: 5
  completed_workload: 0
  task_dependency: [s_t_000]
  required_performance: 
    TRANSPORT: 0 # transport
    MANUFACTURE: 3 # manufacture
  other_attrs:
    category: Solar
s_m_001: # 太陽光発電パネルの展開
  class: Manufacture
  coordinate: [0.0, 5.0]
  total_workload: 5
  completed_workload: 0
  task_dependency: [s_t_001]
  required_performance: 
    TRANSPORT: 0 # transport
    MANUFACTURE: 3 # manufacture
  other_attrs:
    category: Solar
s_m_002: # 太陽光発電パネルの展開
  class: Manufacture
  coordinate: [0.0, 5.0]
  total_workload: 5
  completed_workload: 0
  task_dependency: [s_t_002]
  required_performance: 
    TRANSPORT: 0 # transport
    MANUFACTURE: 3 # manufacture
  other_attrs:
    category: Solar
s_m_003: # 太陽光発電パネルの展開
  class: Manufacture
  coordinate: [0.0, 5.0]
  total_workload: 5
  completed_workload: 0
  task_dependency: [s_t_003]
  required_performance: 
    TRANSPORT: 0 # transport
    MANUFACTURE: 3 # manufacture
  other_attrs:
    category: Solar
s_m_004: # 電源ラインの設置
  class: Manufacture
  coordinate: [0.0, 5.0]
  total_workload: 10
  completed_workload: 0
  task_dependency: []
  required_performance: 
    TRANSPORT: 0 # transport
    MANUFACTURE: 5 # manufacture
  other_attrs:
    category: Solar
s_m_005: # 電源ラインの設置
  class: Manufacture
  coordinate: [0.0, 5.0]
  total_workload: 10
  completed_workload: 0
  task_dependency: []
  required_performance: 
    TRANSPORT: 0 # transport
    MANUFACTURE: 5 # manufacture
  other_attrs:
    category: Solar
t_t_000: # 通信設備の運搬
  class: Transport
  coordinate: [0.0, 0.0]
  total_workload: 5
  completed_workload: 0
  task_dependency: []
  required_performance: 
    TRANSPORT: 4 # transport
    MANUFACTURE: 0 # manufacture
  other_attrs:
    category: Telecom
  origin_coordinate: [0.0, 0.0]  # タスクの始点座標
  destination_coordinate: [-5.0, -5.0]  # タスクの終点座標
  transportability: 0.8  # タスクの運搬難度（0.0~1.0）
t_t_001: # 通信設備の運搬
  class: Transport
  coordinate: [0.0, 0.0]
  total_workload: 5
  completed_workload: 0
  task_dependency: []
  required_performance: 
    TRANSPORT: 4 # transport
    MANUFACTURE: 0 # manufacture
  other_attrs:
    category: Telecom
  origin_coordinate: [0.0, 0.0]  # タスクの始点座標
  destination_coordinate: [-5.0, -5.0]  # タスクの終点座標
  transportability: 0.8  # タスクの運搬難度（0.0~1.0）
t_m_000: # 通信設備の組み立て
  class: Manufacture
  coordinate: [-5.0, -5.0]
  total_workload: 10
  completed_workload: 0
  task_dependency: [t_t_000]
  required_performance: 
    TRANSPORT: 0 # transport
    MANUFACTURE: 5 # manufacture
  other_attrs:
    category: Solar
t_m_001: # 通信設備の組み立て
  class: Manufacture
  coordinate: [-5.0, -5.0]
  total_workload: 10
  completed_workload: 0
  task_dependency: [t_t_001]
  required_performance: 
    TRANSPORT: 0 # transport
    MANUFACTURE: 8 # manufacture
  other_attrs:
    category: Solar