config_dir:
  module_type: ./configs/20250414//module_type.yaml
  module: ./configs/20250414/module.yaml
  robot_type: ./configs/20250414//robot_type.yaml
module:
  seed: 1234
  coodinate_set:
    - [0.0, 0.0]
    - [6.0, 8.0]
    - [0.0, 5.0]
    - [-5.0, 0.0]
  operating_time_set: 
    - 0.0
    - 5.0
    - 10.0
  total_modules: 180
  module_ratio:  # 標準比率
      "Body": [1, 15]
      "Limb": [7, 15]
      "EndE": [3, 15]
      "Wheel": [4, 15]
robot:
  TWSH:
    performance: !PerformanceAttributes
      TRANSPORT: 3
      MANUFACTURE: 2
      MOBILITY: 3
  TWDH:
    performance: !PerformanceAttributes
      TRANSPORT: 2
      MANUFACTURE: 5
      MOBILITY: 3
  QWSH:
    performance: !PerformanceAttributes
      TRANSPORT: 5
      MANUFACTURE: 2
      MOBILITY: 3
  QWDH:
    performance: !PerformanceAttributes
      TRANSPORT: 4
      MANUFACTURE: 5
      MOBILITY: 3
  Dragon:
    performance: !PerformanceAttributes
      TRANSPORT: 2
      MANUFACTURE: 2
      MOBILITY: 3
  Minimal:
    performance: !PerformanceAttributes
      TRANSPORT: 0
      MANUFACTURE: 1
      MOBILITY: 1