task: ./configs/sample000/task.yaml
task_dependency: ./configs/sample000/task_dependency.yaml
module_type: ./configs/sample000/module_type.yaml
module: ./configs/sample000/module.yaml
robot_type: ./configs/sample000/robot_type.yaml
robot: ./configs/sample000/robot.yaml
risk_scenario: ./configs/sample000/risk_scenario.yaml
task_priority: ./configs/sample000/task_priority.yaml


framework:
  training_scenario: [scenario_00, scenario_01, scenario_02, scenario_03, scenario_04]
  test_scenario: [scenario_05]
  totalIteration: 3
architecture:
  populationSize: 20
  seed: 1234
  totalTrials: 2000
  maxRobot: 20
  miminalActive: 2
  miminalSpare: 0.1
  objective: ['WeightedPerformance', 'TotalRedundancy', 'ModuleMovement']
  constraint: ['ActiveRobot']
schedule:
  populationSize: 10
  eliteSize: 1
  generations: 100
  seed: 1234
  totalTrials: 500
  
  