twsh_000:
  name: twsh_000
  robot_type: TWSH
  coordinate: [0.0, 0.0]
  component: [body_00, limb_00, limb_01, limb_02, limb_03, ende_00, wheel_00, wheel_01, wheel_02]
twdh_000:
  name: twdh_000
  robot_type: TWDH
  coordinate: [0.0, 0.0]
  component: [body_01, limb_04, limb_05, limb_06, limb_07, limb_08, ende_01, ende_02, wheel_03, wheel_04, wheel_05]
qwsh_000:
  name: qwsh_000
  robot_type: QWSH
  coordinate: [0.0, 0.0]
  component: [body_02, limb_09, limb_10, limb_11, limb_12, limb_13, ende_03, wheel_06, wheel_07, wheel_08, wheel_09]
qwdh_000:
  name: qwdh_000
  robot_type: QWDH
  coordinate: [0.0, 0.0]
  component: [body_03, limb_14, limb_15, limb_16, limb_17, limb_18, limb_19, ende_04, ende_05, wheel_10, wheel_11, wheel_12, wheel_13]
dragon_000:
  name: dragon_000
  robot_type: Dragon
  coordinate: [0.0, 0.0]
  component: [limb_20, limb_21, ende_06, wheel_14, wheel_15]
minimal_000:
  name: minimal_000
  robot_type: Minimal
  coordinate: [0.0, 0.0]
  component: [limb_22, ende_07, wheel_16]
minimal_001:
  name: minimal_001
  robot_type: Minimal
  coordinate: [0.0, 0.0]
  component: [limb_23, ende_08, wheel_17]