m_000:
  module_type: Body
  coordinate:
  - 0.0
  - 0.0
  battery: 1
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_001:
  module_type: Body
  coordinate:
  - 0.0
  - 0.0
  battery: 1
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_002:
  module_type: Body
  coordinate:
  - 0.0
  - 0.0
  battery: 1
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_003:
  module_type: Body
  coordinate:
  - 0.0
  - 0.0
  battery: 1
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_004:
  module_type: Body
  coordinate:
  - 0.0
  - 0.0
  battery: 1
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_005:
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_006:
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_007:
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_008:
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_009:
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_010:
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_011:
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_012:
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_013:
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_014:
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_015:
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_016:
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_017:
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_018:
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_019:
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_020:
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_021:
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_022:
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_023:
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_024:
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_025:
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_026:
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_027:
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_028:
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_029:
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_030:
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_031:
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_032:
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_033:
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_034:
  module_type: Limb
  coordinate:
  - 0.0
  - 0.0
  battery: 5
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_035:
  module_type: EndE
  coordinate:
  - 0.0
  - 0.0
  battery: 1
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_036:
  module_type: EndE
  coordinate:
  - 0.0
  - 0.0
  battery: 1
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_037:
  module_type: EndE
  coordinate:
  - 0.0
  - 0.0
  battery: 1
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_038:
  module_type: EndE
  coordinate:
  - 0.0
  - 0.0
  battery: 1
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_039:
  module_type: EndE
  coordinate:
  - 0.0
  - 0.0
  battery: 1
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_040:
  module_type: EndE
  coordinate:
  - 0.0
  - 0.0
  battery: 1
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_041:
  module_type: EndE
  coordinate:
  - 0.0
  - 0.0
  battery: 1
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_042:
  module_type: EndE
  coordinate:
  - 0.0
  - 0.0
  battery: 1
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_043:
  module_type: EndE
  coordinate:
  - 0.0
  - 0.0
  battery: 1
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_044:
  module_type: EndE
  coordinate:
  - 0.0
  - 0.0
  battery: 1
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_045:
  module_type: Wheel
  coordinate:
  - 0.0
  - 0.0
  battery: 15
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_046:
  module_type: Wheel
  coordinate:
  - 0.0
  - 0.0
  battery: 15
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_047:
  module_type: Wheel
  coordinate:
  - 0.0
  - 0.0
  battery: 15
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_048:
  module_type: Wheel
  coordinate:
  - 0.0
  - 0.0
  battery: 15
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_049:
  module_type: Wheel
  coordinate:
  - 0.0
  - 0.0
  battery: 15
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_050:
  module_type: Wheel
  coordinate:
  - 0.0
  - 0.0
  battery: 15
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_051:
  module_type: Wheel
  coordinate:
  - 0.0
  - 0.0
  battery: 15
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_052:
  module_type: Wheel
  coordinate:
  - 0.0
  - 0.0
  battery: 15
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_053:
  module_type: Wheel
  coordinate:
  - 0.0
  - 0.0
  battery: 15
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_054:
  module_type: Wheel
  coordinate:
  - 0.0
  - 0.0
  battery: 15
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_055:
  module_type: Wheel
  coordinate:
  - 0.0
  - 0.0
  battery: 15
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_056:
  module_type: Wheel
  coordinate:
  - 0.0
  - 0.0
  battery: 15
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_057:
  module_type: Wheel
  coordinate:
  - 0.0
  - 0.0
  battery: 15
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_058:
  module_type: Wheel
  coordinate:
  - 0.0
  - 0.0
  battery: 15
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_059:
  module_type: Wheel
  coordinate:
  - 0.0
  - 0.0
  battery: 15
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_060:
  module_type: Wheel
  coordinate:
  - 0.0
  - 0.0
  battery: 15
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_061:
  module_type: Wheel
  coordinate:
  - 0.0
  - 0.0
  battery: 15
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_062:
  module_type: Wheel
  coordinate:
  - 0.0
  - 0.0
  battery: 15
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_063:
  module_type: Wheel
  coordinate:
  - 0.0
  - 0.0
  battery: 15
  operating_time: 0.0
  state: !ModuleState ACTIVE
m_064:
  module_type: Wheel
  coordinate:
  - 0.0
  - 0.0
  battery: 15
  operating_time: 0.0
  state: !ModuleState ACTIVE
