coordinate_set:
- [6.0, 8.0]
- [0.0, 5.0]
- [-5.0, 0.0]
task:
  number: 10
  class:
  - Transport
  - Manufacture
  class_rate:
  - 0.5
  - 0.5
  location_variance: 0.5
  performance_max: 15
  performance_min: 5
  dependency_depth: 3
  dependency_influence: 3.0
module:
  number:
    Body: 5
    Limb: 30
    EndE: 10
    Wheel: 20
rsik_scenario:
  class: TimeSigmoid
  sharpness: 10.0
  limit: 50
seed: 1234
scenario: scenario_00
max_step: 50
charge_station:
  base_00: # 基地
    name: base_00
    coordinate: [0.0, 0.0]
    charging_speed: 10