load:
  task: ./configs/quick_sample_000/task.yaml
  task_dependency: ./configs/quick_sample_000/task_dependency.yaml
  module_type: ./configs/quick_sample_000/module_type.yaml
  module: ./configs/quick_sample_000/module.yaml
  robot_type: ./configs/quick_sample_000/robot_type.yaml
  robot: ./configs/quick_sample_000/robot.yaml
  map: ./configs/quick_sample_000/map.yaml
  risk_scenario: ./configs/quick_sample_000/risk_scenario.yaml
  task_priority: ./configs/quick_sample_000/task_priority.yaml

save:
  task: ./results/quick_sample_000/task.yaml
  task_dependency: ./results/quick_sample_000/task_dependency.yaml
  module_type: ./results/quick_sample_000/module_type.yaml
  module: ./results/quick_sample_000/module.yaml
  robot_type: ./results/quick_sample_000/robot_type.yaml
  robot: ./results/quick_sample_000/robot.yaml
  map: ./results/quick_sample_000/map.yaml
  risk_scenario: ./results/quick_sample_000/risk_scenario.yaml
  task_priority: ./results/quick_sample_000/task_priority.yaml

simulation:
  max_step: 50
  training_scenarios: [[s_000], [s_001], [s_002], [s_003], [s_004]]
  test_scenarios: [[s_005]]