load:
  task: ./configs/quick_sample_000/task.yaml
  task_dependency: ./configs/quick_sample_000/task_dependency.yaml
  module_type: ./configs/quick_sample_000/module_type.yaml
  module: ./configs/quick_sample_000/module.yaml
  robot_type: ./configs/quick_sample_000/robot_type.yaml
  robot: ./configs/quick_sample_000/robot.yaml
  map: ./configs/quick_sample_000/map.yaml
  risk_scenario: ./configs/quick_sample_000/risk_scenario.yaml
  task_priority: ./configs/quick_sample_000/task_priority.yaml

save:
  task: ./results/quick_sample_000/task.yaml
  task_dependency: ./results/quick_sample_000/task_dependency.yaml
  module_type: ./results/quick_sample_000/module_type.yaml
  module: ./results/quick_sample_000/module.yaml
  robot_type: ./results/quick_sample_000/robot_type.yaml
  robot: ./results/quick_sample_000/robot.yaml
  map: ./results/quick_sample_000/map.yaml
  risk_scenario: ./results/quick_sample_000/risk_scenario.yaml
  task_priority: ./results/quick_sample_000/task_priority.yaml

results:
  task: ./results/quick_sample_000/history/task{index:03}.pkl
  module: ./results/quick_sample_000/history/module{index:03}.pkl
  robot: ./results/quick_sample_000/history/robot{index:03}.pkl

figure:
  task_dependency: ./results/quick_sample_000/figure/task_dependency.pdf
  workload_pie: ./results/quick_sample_000/history/workload_pie_{index:03}.pdf

simulation:
  max_step: 50
  training_scenarios: [[s_000], [s_001], [s_002], [s_003]]
  varidate_scenarios: [s_004]

task_allocation:
  populationSize: 10
  generations: 100
  seed: 1234
