TWSH:
  required_modules:
    Body: 1
    Limb: 4
    EndE: 1
    Wheel: 3
  performance: !PerformanceAttributes
    TRANSPORT: 3
    MANUFACTURE: 3
    MOBILITY: 3
  power_consumption: 1
  recharge_trigger: 10
TWDH:
  required_modules:
    Body: 1
    Limb: 5
    EndE: 2
    Wheel: 3
  performance: !PerformanceAttributes
    TRANSPORT: 3
    MANUFACTURE: 5
    MOBILITY: 3
  power_consumption: 1
  recharge_trigger: 10
QWSH:
  required_modules:
    Body: 1
    Limb: 5
    EndE: 1
    Wheel: 4
  performance: !PerformanceAttributes
    TRANSPORT: 4
    MANUFACTURE: 3
    MOBILITY: 3
  power_consumption: 1
  recharge_trigger: 10
QWDH:
  required_modules:
    Body: 1
    Limb: 6
    EndE: 2
    Wheel: 4
  performance: !PerformanceAttributes
    TRANSPORT: 4
    MANUFACTURE: 4
    MOBILITY: 3
  power_consumption: 1
  recharge_trigger: 10
Dragon:
  required_modules:
    Body: 0
    Limb: 2
    EndE: 1
    Wheel: 2
  performance: !PerformanceAttributes
    TRANSPORT: 1
    MANUFACTURE: 2
    MOBILITY: 2
  power_consumption: 1
  recharge_trigger: 10
Minimal:
  required_modules:
    Body: 0
    Limb: 1
    EndE: 1
    Wheel: 1
  performance: !PerformanceAttributes
    TRANSPORT: 1
    MANUFACTURE: 2
    MOBILITY: 1
  power_consumption: 1
  recharge_trigger: 10